# -*- coding: utf-8 -*-
"""Titanic Survival Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojemBxiHzSa7QBNr6L6RlPlfE_CCt2wN
"""



"""#  Titanic Survival Analysis

This notebook analyzes the Titanic dataset to explore patterns in passenger survival.

**Tools used**: pandas, seaborn, matplotlib  
**Dataset source**: [Data Science Dojo on GitHub](https://github.com/datasciencedojo/datasets)



"""

#  1. Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#  2. Load the dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

#  Preview first rows
df.head()

"""##  Dataset Overview

We begin by inspecting the structure of the dataset, statistical summaries, and missing values.

"""

# Dataset information
df.info()

# Descriptive statistics
df.describe()

# Missing values
df.isnull().sum()

"""##  Data Cleaning

- Fill missing values in the `Age` column with the mean
- Drop the `Cabin` column due to too many missing values

"""

# Fill missing ages with the mean
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Drop the 'Cabin' column
df.drop(columns=['Cabin'], inplace=True)

"""##  Visualizations

We visualize:
- Total survival count
- Survival rate by passenger class
- Survival rate by gender

"""

sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Number of Passengers")
plt.show()

sns.barplot(x='Pclass', y='Survived', data=df)
plt.title("Survival Rate by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Survival Rate")
plt.show()

sns.barplot(x='Sex', y='Survived', data=df)
plt.title("Survival Rate by Gender")
plt.xlabel("Gender")
plt.ylabel("Survival Rate")
plt.show()

"""##  Conclusion

- Female passengers had a significantly higher survival rate.
- Passengers in first class were more likely to survive.
- Data cleaning is essential for accurate analysis.

---

 Created by Randa LAKAB | Published via Google Colab

"""